title: <p align="center"> Shashi Bhushan </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/shashi-bhushan-singh-520a9315a/">LinkedIn</a> |
  <a href="https://github.com/01061993">GitHub</a>
  
  <br>   
  I'm working as application developer.
  Also handing the Big Data from real-time Ad call data.
  Worked with IBM Research at Big Data Analytics team.
  Working in AdTech domain for 3 years.
  <br>
  </p>
  
theme: jekyll-theme-minimal
