title: <p align="center"> Shashi Bhushan </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/shashi-bhushan-singh-520a9315a/">LinkedIn</a> |
  <a href="https://github.com/01061993">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Working in a Telecom domain for 5 years.
  <br>
  </p>

theme: jekyll-theme-minimal